library;

export 'home/home_index/index.dart';
export 'home/matching_detail/index.dart';
export 'msg/chat/index.dart';
export 'msg/msg_index/index.dart';
export 'my/edit/index.dart';
export 'my/edit_profile/index.dart';
export 'my/edit_profile_info/index.dart';
export 'my/my_index/index.dart';
export 'posts/send_post/index.dart';
export 'posts/posts_index/index.dart';
export 'posts/post_detal/index.dart';
export 'system/login/index.dart';
export 'system/main/index.dart';
export 'system/register/register_basic_information/index.dart';
export 'system/register/register_index/index.dart';
export 'system/register/register_upload_picture/index.dart';
export 'system/register/select_country/index.dart';
export 'system/register/select_language/index.dart';
export 'system/settings/about_us/index.dart';
export 'system/settings/privacy agreement/index.dart';
export 'system/settings/settings_index/index.dart';
export 'system/settings/user_agreement/index.dart';
export 'system/splash/index.dart';
export 'system/welcome/index.dart';
